name       : optipng
version    : 0.7.6
release    : 2
source     :
    - http://liquidtelecom.dl.sourceforge.net/project/optipng/OptiPNG/optipng-0.7.6/optipng-0.7.6.tar.gz : 4870631fcbd3825605f00a168b8debf44ea1cda8ef98a73e5411eee97199be80
license    : ZLIB
summary    : PNG optimizer recompresses image files to a smaller size, without losing any information
component  : multimedia.library
description: |
    PNG optimizer recompresses image files to a smaller size, without losing any information
setup      : |
    ./configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
