name       : optipng
version    : 0.7.7
release    : 3
source     :
    - https://nchc.dl.sourceforge.net/project/optipng/OptiPNG/optipng-0.7.7/optipng-0.7.7.tar.gz : 4f32f233cef870b3f95d3ad6428bfe4224ef34908f1b42b0badf858216654452
license    : Zlib
summary    : PNG optimizer recompresses image files to a smaller size, without losing any information
component  : multimedia.library
description: |
    PNG optimizer recompresses image files to a smaller size, without losing any information
setup      : |
    ./configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
