name       : optipng
version    : 0.7.5
release    : 1
source     :
    - http://liquidtelecom.dl.sourceforge.net/project/optipng/OptiPNG/optipng-0.7.5/optipng-0.7.5.tar.gz : 74e54b798b012dff8993fb8d90185ca83f18cfa4935f4a93b0bcfc33c849619d
license    : ZLIB
summary    : PNG optimizer recompresses image files to a smaller size, without losing any information
description: |
    PNG optimizer recompresses image files to a smaller size, without losing any information
builddeps  :
setup      : |
    ./configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
